### ISSUE TITLE
打包后cdn问题

### ISSUE THREAD

**Issue by 672064406zerui** [HaoChuan9421/vue-optimization#1]
打包之前引入的 高德js 在打包后，完全不一样了，从https都到http了 而且引入的东西也不同。
而静态引入的vue js 等的cdn 打包后也不见了，你demo的方式 是首页服务端渲染的那种模式，往里塞js的吗？
现在打包后资源问题出错。不知该如何解决。ejs的方式，我不那样引入，静态引入打包就不行吗

**Comment by haochuan9421** [comment]
你完全可以直接把link或者script标签写在index.html里，不需要照搬我那种，我那么做的原因是：可能有些人不希望开发的时候使用CDN链接，而在build的时候使用，这样他们就可以通过判断NODE_ENV来动态改变config下的配置

**Comment by haochuan9421** [comment]
预渲染其实并不会影响最后哪些标签插入进入，主要是htmlWebpackPlugin的作用

**Comment by 672064406zerui** [comment]
方便加个微信么，我这有点问题，我都研究挺久了，现在的话  按照插件官网的配置，最后进行谷歌内部测试，然后那一步总是有报错
Uncaught SyntaxError: Unexpected token <
然后无法打包
 new PrerenderSPAPlugin({
      staticDir: config.build.assetsRoot,
      routes: [
        '/', '/hotelsearch'
      ], // 需要预渲染的路由
      renderer: new Renderer({
        inject: {
          foo: 'bar'
        },
        headless: false,
        renderAfterDocumentEvent: 'render-event'
      }),
      minify: {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        keepClosingSlash: true,
        sortAttributes: true
      },
      postProcess(renderedRoute) {
        renderedRoute.html = renderedRoute
          .html
          .replace(/<script.*src=".*[0-9]+\.[0-9a-z]*\.js"><\/script>/, '')
        return renderedRoute
      }
    }),
这是我的配置项。然后我就没动什么了，只是在index html 自己引入了一些vue的cdn ，配置项里，我是不打包依赖里的vue那些的。之后就是报错，无法打包

**Comment by 672064406zerui** [comment]
而且cdn 那块，照你那么做的话，以前我就弄过，但是开发的时候，总是报错Vue 找不到。然后就用了引入cdn。配置项里打包去掉vue的这种做法。能告诉我为什么吗

**Comment by haochuan9421** [comment]
可以，你把你微信发我邮箱里吧

**Comment by 672064406zerui** [comment]
谢谢 发过去了
