### ISSUE TITLE
改成引用CDN后  打包完放到测试环境 报错：[vuex] already installed. Vue.use(Vuex) should be called only once.

### ISSUE THREAD

**Issue by Deeeeeee** [HaoChuan9421/vue-optimization#2]
Google 了一下， 在外部引用vuex后，store/index.js 中无需再次 Vue.use(Vuex)。
示例代码中 有 Vue.use(Vuex)，而且打包完成后 没有报错。
想请教一下是如何避免的

**Comment by haochuan9421** [comment]
你说的没错，element-ui也是一样，谢谢提醒

**Comment by haochuan9421** [comment]
但是报错应该不会吧？

**Comment by Deeeeeee** [comment]
示例代码 打包完是没报错的。
我这边打包完 报了上面的错误， 想请教一下，如何避免的

**Comment by haochuan9421** [comment]
如果报错了判断一个NODE_ENV

**Comment by Deeeeeee** [comment]
@HaoChuan9421 好的，我也是这样想的。 但是很好奇为什么示例代码中没有报错。（我先这样判断一下， 后面再好好研究一下示例）。 多谢啦

**Comment by haochuan9421** [comment]
![image](https://user-images.githubusercontent.com/5093611/47076295-fd049800-d230-11e8-9b28-7d62f13a10b0.png)

**Comment by haochuan9421** [comment]
![image](https://user-images.githubusercontent.com/5093611/47076335-14438580-d231-11e8-85f0-be1f541fb9a2.png)

**Comment by Deeeeeee** [comment]
@HaoChuan9421 
事实上 并没有影响项目正常运行，只是抛出了这样的一个错误。 已经阻止了多次注册
![image](https://user-images.githubusercontent.com/14084787/47076408-389f6200-d231-11e8-9e29-f9ca97f02ffa.png)

**Comment by haochuan9421** [comment]
![image](https://user-images.githubusercontent.com/5093611/47076577-a21f7080-d231-11e8-98bd-3e16ce3f13c6.png)

**Comment by haochuan9421** [comment]
刚才分析了一下Vue和Vuex的源码，发现设计的还是比较严谨的：
1. 首先是Vue，在调用Vue.use的时候，会判断是否已经install，如果执行过会直接return,不会调用第二次，就是说，如果你连续执行多次同一个Vue.use(xxx)，他也只会调用一次xxx的install方法
![image](https://user-images.githubusercontent.com/5093611/47083841-75c11f80-d244-11e8-884e-2918f8ee538f.png)

2. 其次就是Vuex，他是通过工厂函数返回Vuex对象的，函数内部有一个局部的Vue变量，在没有执行install方法之前它是undefined，执行之后这个内部的Vue变量就会被赋值为外部的Vue变量，如果install第二次被调用，那么内部的Vue会存在，并且全等于外部的Vue,此时才会抛出你那个错误。
![image](https://user-images.githubusercontent.com/5093611/47084064-11eb2680-d245-11e8-9872-2ba3fa59d73f.png)
Vuex还有一点严谨之处在于，当你没有使用Vue.use(xxx)去install的时候，而是直接调用new Vuex.Store()的时候，如果window存在Vue对象而内部Vue变量为undefined，也就是说没有执行过install，它也会自动为你安装，就好比使用CDN外链引入的时候。
![image](https://user-images.githubusercontent.com/5093611/47085056-051c0200-d248-11e8-9166-8a9e59eff064.png)

所以很好奇你是怎么绕过这么多层检测，让它报错的😂
