### ISSUE TITLE
使用CDN之后如何覆盖element-ui本身的变量

### ISSUE THREAD

**Issue by yangzheng93** [HaoChuan9421/vue-optimization#3]
element-ui的主题variables如何在使用cdn之后进行覆盖？
[Docs](http://element-cn.eleme.io/#/zh-CN/component/custom-theme#zai-xiang-mu-zhong-gai-bian-scss-bian-liang)

**Comment by haochuan9421** [comment]
你要是需要自定义主题，element-ui的css就不能通过CDN引入了

**Comment by yangzheng93** [comment]
> 你要是需要自定义主题，element-ui的css就不能通过CDN引入了

好，我试一下，thanks
